// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8qhLpUV8KNDFIL_NESQ0rUPfQNDWkpgI',
    appId: '1:975624378954:web:bdeb8fcf38df4b8b7be4b3',
    messagingSenderId: '975624378954',
    projectId: 'lightev-6b431',
    authDomain: 'lightev-6b431.firebaseapp.com',
    databaseURL: 'https://lightev-6b431-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lightev-6b431.firebasestorage.app',
    measurementId: 'G-1LWPEFWMNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChWExQrYmKvc4qyXFjKugNlGK8JgIbEdY',
    appId: '1:975624378954:android:0bda5de28dcc58f77be4b3',
    messagingSenderId: '975624378954',
    projectId: 'lightev-6b431',
    databaseURL: 'https://lightev-6b431-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lightev-6b431.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnn3eKFUMtfZ_HD9UJ3CJNPiRrr6pjSdM',
    appId: '1:975624378954:ios:3db16000928cfd9b7be4b3',
    messagingSenderId: '975624378954',
    projectId: 'lightev-6b431',
    databaseURL: 'https://lightev-6b431-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lightev-6b431.firebasestorage.app',
    iosBundleId: 'com.example.ev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnn3eKFUMtfZ_HD9UJ3CJNPiRrr6pjSdM',
    appId: '1:975624378954:ios:3db16000928cfd9b7be4b3',
    messagingSenderId: '975624378954',
    projectId: 'lightev-6b431',
    databaseURL: 'https://lightev-6b431-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lightev-6b431.firebasestorage.app',
    iosBundleId: 'com.example.ev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8qhLpUV8KNDFIL_NESQ0rUPfQNDWkpgI',
    appId: '1:975624378954:web:4cadffa1c9f0e06d7be4b3',
    messagingSenderId: '975624378954',
    projectId: 'lightev-6b431',
    authDomain: 'lightev-6b431.firebaseapp.com',
    databaseURL: 'https://lightev-6b431-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lightev-6b431.firebasestorage.app',
    measurementId: 'G-BC29J13R0L',
  );
}
